### ISSUE TITLE
Make Promises Great Again

### ISSUE THREAD

**Issue by jwulf** [KoryNunn/righto#26]
Dumb question: 

Could you have something like util.Promisify?

Like:

```
function rightoify(somePromise) {
    return righto(function(somePromiseResult, done){
        done(null, somePromiseResult);
    }, somePromise);
}
```

**Comment by KoryNunn** [comment]
As in to turn a promise into a righto?
`righto.from(promise)`

Or to turn a promise-function (like an async function) into a lazy- resolving righto?
`righto.sync(asyncFunction, even, with, eventual, args)`

**Comment by KoryNunn** [comment]
These are both documented in the readme btw: https://github.com/KoryNunn/righto#sync
