### ISSUE TITLE
Wanted to fix Readme / but not a contributer

### ISSUE THREAD

**Issue by classicCokie** [KoryNunn/righto#29]
Hellou there old friend, 

I wanted to use righto, and found an error in your ReadMe. Wanted to create a PR for it, but I ain't no contributer. So SAD!

Would love the rights to create PRs.

Cheers

**Comment by KoryNunn** [comment]
Hey! You should be able to create a PR from a fork, you won't need to be a contributer. I would have thought clicking the edit button on the range would prompt you to fork automatically?
